---
name: Calendar Plugin
description: A built-in module for integrating Google Calendar with Ark 2.0

functions:
  get_event:
    description: Retrieve details of a calendar event.
    parameters:
      event_name:
        type: str
        required: true
    return_type: str

  update_event:
    description: Modify an existing calendar event.
    parameters:
      event_name:
        type: str
        required: true
      updates:
        type: dict
        required: true
    return_type: str

  delete_event:
    description: Remove an event from the calendar.
    parameters:
      event_name:
        type: str
        required: true
    return_type: str

dependencies:
  auth:
    GoogleAuth: true
  state:
    cal_state: # developer-defined JSON based state

